:scheduler:
  :schedule:
    scheduler_worker:
      cron: "* * * * *"  # Runs every minute
      class: SchedulerWorker
    active_time_worker:
      cron: "*/5 * * * *"  # Runs every 5 minutes
      class: "ActiveTimeWorker"
    my_worker:
      cron: "0 * * * *"  # Runs every hour
      class: "MyWorker"  # Add your worker class name here

:redis:
  :url: redis://localhost:6379/0

:concurrency: 5
:queues:
  - default
